[package]
name = "tempest"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.102"
dotenvy = "0.15.7"
toml = "1.1.2"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt", "json"] }
tracing = "0.1.44"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
walkdir = "2.5"
colored = "3.1.1"
enum_dispatch = "0.3.13"
serde_yml = "0.0.12"
reqwest = { version = "0.13.3", features = ["json"] }
async-trait = "0.1.89"
serde_json = "1.0.149"
async-recursion = "1.1.1"
cel-interpreter = "0.10.0"
liquid = "0.26"
liquid-core = "0.26"
include_dir = "0.7"