name: PR - Clippy

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [main]
    paths:
      - "tempest/**"
      - ".github/workflows/pr-test-clippy.yml"

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ./tempest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Clippy
        run: rustup component add clippy

      - name: Cargo Check
        run: cargo clippy --all-targets --all-features -- -D warnings
